export const data = [
  {
    id: 1,
    img: 'https://www.pngall.com/wp-content/uploads/7/Blouse-PNG-HD-Image.png',
    desc: 'description 1',
    title: 'productName 1',
    price: 25,
    amount: 1,
  },
  {
    id: 2,
    img: 'https://www.pngall.com/wp-content/uploads/7/Blouse.png',
    desc: 'description 2',
    title: 'productName 2',
    price: 30,
    amount: 1,
  },
  {
    id: 3,
    img: 'https://www.pngall.com/wp-content/uploads/12/Jumper-Sweater-PNG-Image-HD.png',
    desc: 'description 3',
    title: 'productName 3',
    price: 27,
    amount: 1,
  },
  {
    id: 4,
    img: 'https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png',
    desc: 'description 4',
    title: 'productName 4',
    price: 24,
    amount: 1,
  },
  {
    id: 5,
    img: 'https://www.pngall.com/wp-content/uploads/12/Jumper-Sweater-PNG-Clipart.png',
    desc: 'description 5',
    title: 'productName 5',
    price: 26,
    amount: 1,
  },
  {
    id: 6,
    img: 'https://www.pngall.com/wp-content/uploads/2016/07/Dress-PNG-HD.png',
    desc: 'description 6',
    title: 'productName 6',
    price: 20,
    amount: 1,
  },
  {
    id: 7,
    img: 'https://www.pngall.com/wp-content/uploads/12/Jumper-Sweater-PNG.png',
    desc: 'description 7',
    title: 'productName 7',
    price: 21,
    amount: 1,
  },
  {
    id: 8,
    img: 'https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png',
    desc: 'description 8',
    title: 'productName 8',
    price: 22,
    amount: 1,
  },
]

export const slides = [
  {
    id: 1,
    img: 'https://i.ibb.co/cXFnLLV/3.png',
    title: 'Открой для себя лето!',
    desc: 'Не отказывай себе в своих желаниях.',
    bgColor: '#fbf0f4',
  },
  {
    id: 2,
    img: 'https://i.ibb.co/DG69bQ4/2.png',
    title: 'Летняя коллекция уже в продаже.',
    desc: 'Почувствуй легкость грядущего дня.',
    bgColor: 'yellow',
  },
  {
    id: 3,
    img: 'https://i.ibb.co/DG69bQ4/2.png',
    title: 'Летняя коллекция уже в продаже.',
    desc: 'Почувствуй легкость грядущего дня.',
    bgColor: 'grey',
  },
]
